# Generated by Django 2.2 on 2020-10-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producttable',
            table='products_table',
        ),
    ]
