# Generated by Django 2.2 on 2020-10-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
