# Generated by Django 2.2 on 2020-10-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
