# Generated by Django 2.2 on 2020-10-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201022_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='password',
        ),
    ]
