# Generated by Django 2.2 on 2020-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_usertable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
