# Generated by Django 2.2 on 2020-10-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_usertable_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user_id',
        ),
    ]
